### ISSUE TITLE
Function Declarations in the Fortran Header

### ISSUE THREAD

**Issue by jdinan** [openshmem-org/specification#1]
The spec is not clear enough about what should be contained in shmem.fh.  At present, shmem.fh varies across implementations, falling roughly into two camps:

1. shmem.fh contains *no* function declaraions; users must declare SHMEM functions in their code
2. shmem.fh contains *all* function declarations; users do not declare SHMEM functions in their code

The requirements on shmem.fh should be clarified.

**Comment by swpoole** [comment]
Agreed.

Best wishes
Steve...

**Comment by shamisp** [comment]
For now I would avoid opening of specification tickets on github bug tracker since all the rest tickets are managed on redmine. @jdinan - can you please open the issue on redmine ? As a community we would have to plan (if we decide to do so) the transition from redmine ticket system to github. IMHO it would be a bad idea to have the tickets scattered all over the place. My 0.01$. Pasha.

**Comment by jdinan** [comment]
Moved to isse #203 on redmine: http://www.openshmem.org/redmine/issues/203
