### ISSUE TITLE
Do deprecated atomics have ctx versions?

### ISSUE THREAD

**Issue by BryantLam** [openshmem-org/specification#185]
When the old atomic names were deprecated in #31, this language was added in the Notes section of the new atomic routines:
>   As of OpenSHMEM 1.4, _shmem_fetch_ has been deprecated. Its behavior and call signature are identical to the replacement  interface,  _shmem_atomic_fetch_.

Then contexts were ratified in #63 and expanded all AMOs with ctx versions (_shmem_ctx_atomic_fetch_).

The current language implies that _shmem_fetch_ is an alias for _shmem_atomic_fetch_ (and therefore can be implemented as a `#define`). As of now, [backmatter is expanding the old atomic entries in the deprecation annex to be more explicit](https://github.com/openshmem-org/specification/pull/118/commits/0bc7b4ad54d2560aff0c59058bc2f90e92a3a5ba#diff-3b37f8686e2f1bb2e5cb250aa60d8d16R514), but now I'm unsure whether the ctx versions are intended to be supported and are therefore not listed currently. Either the deprecation needs to change or the Notes section needs to change for the affected AMOs.

**Comment by nspark** [comment]
I was thinking of revising the "Notes" section to say:

> As of OpenSHMEM 1.4, _shmem_fetch_ has been deprecated. Its behavior and call signature are identical to the replacement  interface, _shmem_atomic_fetch_, subject to the following constraints:
> - _shmem_fetch_ does not accept a context argument
> - _shmem_fetch_ is only supported for _float_, _double_, _int_, _long_, and _long long_ types

I considered being explicit and saying "subject to the following constraints (as specified by OpenSHMEM 1.3)". This also only implicitly refers to _shmem_TYPENAME_fetch_, since we typically refer to functions in groups when possible. To be totally explicit, we would have to say something like:

> As of OpenSHMEM 1.4, the _C_ and _C11_ interfaces _shmem_fetch_ and _shmem_TYPENAME_fetch_ have been deprecated. Their behavior and call signature are identical to the respective replacement  interfaces, _shmem_atomic_fetch_ and _shmem_TYPENAME_atomic_fetch_, subject to the constraints that the deprecated interfaces do not accept a context argument and are only supported for _float_, _double_, _int_, _long_, and _long long_ types.

The constraints imply that an implementation that used `#define shmem_fetch shmem_atomic_fetch` would not be strictly conformant -- and I was a little hesitant to potentially increase the implementation burden for a deprecated API. That said, most implementations could just leave the 1.3 API in place and add the new 1.4 calls, so maybe it's not _additional_ implementation overhead.

I'd definitely like to hear what others think.

**Comment by nspark** [comment]
I opened https://github.com/nspark/specification/pull/6 in case anyone wants to comment directly on the (draft) changes.

**Comment by BryantLam** [comment]
The explicit wording in nspark#6 is good, but I do worry that the current wording doesn't preclude this issue from happening again (e.g., another argument is added). A purely explicit approach would be to use a deprecation block and an explicit types list similar to `shmem_wait` and specify the API up front between the new API and the Fortran synopsis.

**Comment by nspark** [comment]
@BryantLam I'm inclined to go the explicit route and add the full API synopsis within a deprecation block for the now-deprecated APIs. This seems like the most clear and consistent option. Good idea.

**Comment by nspark** [comment]
Closed by https://github.com/nspark/specification/pull/6
