### ISSUE TITLE
Waitsome / Testsome

### ISSUE THREAD

**Issue by davidozog** [openshmem-org/specification#207]
The `shmem_wait_until` and `shmem_test` routines only operate on a single variable.  If users want to wait/test on multiple values, they could avoid the cost of multiple fences if the OpenSHMEM API had "waitsome" and "testsome" routines (analagous to [MPI_Testsome](https://www.mpich.org/static/docs/v3.1/www3/MPI_Testsome.html)/[MPI_Waitsome](https://www.mpich.org/static/docs/v3.1/www3/MPI_Waitsome.html)).

There is also the notion of waiting for "All" or "Any" condition(s), which involves blocking until satisfying _all_ conditions or a _single_ condition, respectively.  One question is whether OpenSHMEM would benefit from these routines, or whether "Some" is sufficient for implementing "All" or "Any" efficiently.

#### Proposed interface for "wait some" and "test some":
```c
void shmem_wait_until_some (TYPE *ivar, size_t nelems, size_t *count, size_t *indices, TYPE cmp, TYPE cmp_value);
int shmem_test_until_some (TYPE *ivar, size_t nelems, size_t *count, size_t *indices, TYPE cmp, TYPE cmp_value);
```

This topic is scheduled for discussion at the RMA WG on ~~March 1st~~ March 15, 2018.  
[Here are the slides](
https://docs.google.com/presentation/d/1vp1XWFE0E2JMUDA5lEdXngEhazETnhJRPwpwDmcqYTM/edit?usp=sharing). 
[ PDF Version here](https://github.com/openshmem-org/specification/files/1768792/RMA.WG.-.Test.2FWaitsome.pdf).

**Comment by nspark** [comment]
Reviewing @davidozog's slides, I recall my main concern when I initially considered such a {wait,&nbsp;test} x {some,&nbsp;all,&nbsp;any} API.

In MPI -- and, of course, since I'm not MPI expert, please correct any errors -- these routines accept an array of opaque `MPI_Request` objects, each of which captures the state of some associated communication operation. These requests can be in one of three states: null, active, or inactive. For the discussion of this API, the main difference between MPI and SHMEM is that an `MPI_Request` object will only change state through local action of the MPI rank; e.g., from null to active via `MPI_Isend` and active to null via `MPI_Wait`.

In contrast, wait variables in SHMEM can change through either local or remote action. Even `shmem_wait_until()` could return indicating the specified condition has been satisfied and an immediate read of the wait variable could return a different value (e.g., if it was remotely updated between the wait and the read). This problem is only exacerbated under a {wait,&nbsp;test} x {some,&nbsp;all,&nbsp;any} API. That is, `shmem_waitall` may return indicating the array of wait variables satisfies the specified condition, and a subsequent read of these variables may indicate otherwise.

I don't think this should preclude OpenSHMEM adding such an API, but I think the specification should be clear about the limitations of what these interfaces can actually provide. Users of these interfaces will need to know that their use model does not assume more than what the API actually provides.

**Comment by nspark** [comment]
@davidozog Here are some minor suggestions on the slides:

* Index and count variables should be of type `size_t`.
* `shmem_test_some` should return the count as `size_t` vs. passing a pointer-to-count as an argument.

**Comment by davidozog** [comment]
Yup, very good point about the difference between MPI and SHMEM here, and why we need to be careful.  IIUC, waitsome/testsome exhibits this problem on its own, correct?

Good catch on the count type, I meant for that to be `size_t`.  I actually did intend for the return value to be a "bool" for success/failure, and the argument to return the count, but I think I like you're idea better...

**Comment by naveen-rn** [comment]
Can we close this issue - I suppose we have added these features for OpenSHMEM-1.5?
