### ISSUE TITLE
Move to Github for proposals  ?

### ISSUE THREAD

**Issue by manjugv** [openshmem-org/specification#58]
Before we completely move away from Redmine and use only github for proposals, we need to backup the Issues, PRs, and Conversations. This issue is to capture the available solutions and track issues related to this.

**Comment by manjugv** [comment]
Pasha's suggestion: https://gist.github.com/rodw/3073987

**Comment by nspark** [comment]
Also, we _can_ add proposal templates, if we want to standardize on a structure for bugs or proposals.

**Comment by swpoole** [comment]
I will check this weekend. We had already done a template for proposals several years ago.

**Comment by nspark** [comment]
@swpoole I was looking at this issue earlier this week, wondering whether we could close it. Template or not, I think we've essentially moved to GitHub for proposals already. I thought @manjugv raised this issue because he wanted to capture the old material on Redmine for reference, however, the link he shared from @shamisp was a script to backup GitHub materials.

@manjugv @shamisp Can you clarify the intent and current status of this issue?

**Comment by manjugv** [comment]
Given that we have essentially moved to github and not using Redmine, we should understand the pros/cons of this transition and help the transition.  The github issue is a placeholder to capture the discussion. This probably involves at least a few issues that we need to understand and address (1) moving the proposals and conversations to github from redmine, (2) back up strategy for github, (3) transition to other git hosts/tools; incase, github goes out of business / we don’t like their service terms. 

(1) This might require a manual transition
(2) is probably addressed by what Pasha is suggesting.
(3) might be easy, since gitlab already supports.

**Comment by jeffhammond** [comment]
I am particularly interested in @shamisp's implementation of
![this](https://camo.githubusercontent.com/aca3e3285f7335ec69a88d107a893c08e6e73bae/687474703a2f2f7777772e746f7069746f2e636f6d2f77702d636f6e74656e742f75706c6f6164732f323031332f30312f636f64652d30332e676966)
 from https://gist.github.com/rodw/3073987.
